version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - PROJECT_ENV=dev
    volumes:
      - ./:/app
    command: yarn start:dev
